### ISSUE TITLE
App is not working in any way

### ISSUE THREAD

**Issue by alishah791** [CogStack/tika-service#11]
**In short nothing worked with this repo. Tried following**

When tried to run this service using tike_service.bat tomcat stucks at this point. Compiled and run with jdk 8 after fixing compile issues

![image](https://user-images.githubusercontent.com/11025501/179708530-9b248dca-3054-41b7-9f26-d7aae1d3d053.png)

Also tried to deploy the war file created using gradlew bootWar and it didn't worked and gave 404 error when deployed on tomcat9

![image](https://user-images.githubusercontent.com/11025501/179711749-4391370e-6112-4845-a499-5dcd04c2ce92.png)

but calling this causes 404

![image](https://user-images.githubusercontent.com/11025501/179711915-85dc5fc2-dc67-4bbf-ae10-de6ba2e5b57d.png)

Tried building the docker file but getting following error
![image](https://user-images.githubusercontent.com/11025501/179716328-b8b5f990-08e7-474f-887c-c56098c5e044.png)

Tried to run docker image and use curl to get the file processed but it is giving garbage text for plain pdf and word docs.

![image](https://user-images.githubusercontent.com/11025501/179716700-e3d54d13-2b85-4c49-aeaa-dae9608b650b.png)

**Comment by vladd-bit** [comment]
Hello,

I have just tested the docker build and it seems to work just fine, what version of Docker are you using ? 

If you want to run the app jar without hassle, do the following:
 
> ./gradlew build
> bash ./build/scripts/tika-service -jar ./build/libs/tika-service-0.4.0-boot.jar

Currently investigating the garbage output.

**Comment by alishah791** [comment]
Docker version 20.10.17, build 100c701

**Comment by vladd-bit** [comment]
All right.

Could you try re-run the docker build and test the files that were getting 400 before ? I did some updates that should have solved the encoding output issue (erroring out), if garbage characters are still being outputted, please set `enforce-encoding-output` to false in the` application.yaml`.

**Comment by vladd-bit** [comment]
Is this still happening? Wanted to know so I can close the ticket .
